name: Render and deploy Quarto project as book and slides

on:
  workflow_call:
    inputs:
      extra-repositories:
        description: 'One or more extra CRAN-like repositories to include in the `repos` global option'
        default: ''
        type: string

jobs:
  render-quarto:
    uses: ./.github/workflows/render_quarto.yml
    
  deploy-quarto:
    runs-on: ubuntu-latest
    needs: render-quarto

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write
      id-token: write

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
